# Generated by Django 3.1.5 on 2021-10-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=2000)),
                ('state', models.CharField(max_length=2000)),
                ('city', models.CharField(max_length=2000)),
                ('branch', models.CharField(max_length=2000)),
                ('fees', models.FloatField()),
                ('package', models.FloatField()),
                ('cet_marks', models.IntegerField()),
                ('jee_marks', models.IntegerField()),
                ('genders_accepted', models.CharField(max_length=2000)),
                ('campus_size', models.CharField(max_length=2000)),
                ('established_year', models.IntegerField()),
                ('rating', models.FloatField()),
                ('university', models.CharField(max_length=2000)),
                ('facilities', models.CharField(max_length=4000)),
                ('college_type', models.CharField(max_length=2000)),
            ],
        ),
    ]
