# Generated by Django 3.1.5 on 2021-10-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='branch',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='campus_size',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='cet_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='city',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='college_type',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='established_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='facilities',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='fees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='genders_accepted',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='institute_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='jee_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='package',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='state',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='university',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
