# Generated by Django 3.1.5 on 2021-10-01 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_auto_20211001_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=2000)),
                ('last_name', models.CharField(blank=True, max_length=2000)),
                ('email', models.CharField(blank=True, max_length=2000, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=2000, null=True)),
                ('college_preference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recommendation.college')),
            ],
        ),
    ]
