# Generated by Django 3.0.4 on 2021-10-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='campus_size',
        ),
        migrations.RemoveField(
            model_name='college',
            name='cet_marks',
        ),
        migrations.RemoveField(
            model_name='college',
            name='college_type',
        ),
        migrations.RemoveField(
            model_name='college',
            name='established_year',
        ),
        migrations.RemoveField(
            model_name='college',
            name='genders_accepted',
        ),
        migrations.RemoveField(
            model_name='college',
            name='jee_marks',
        ),
        migrations.RemoveField(
            model_name='college',
            name='package',
        ),
        migrations.RemoveField(
            model_name='college',
            name='university',
        ),
        migrations.AddField(
            model_name='college',
            name='avg_percentile',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='percentile',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='w1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='w2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='w3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='w4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='w5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='w6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='w7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='w8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='w9',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
